services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USERNAME=postgres
            - POSTGRES_DB=simple_blog_api

    api:
        build: ./
        image: docker.io/srilpok1/simple_blog_api
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_PORT=5432
            - POSTGRES_DB=simple_blog_api
            - PORT=3000
        ports:
            - '8085:3000'
    