-- Create the table
CREATE TABLE episodeIV (
    name STRING,
    line STRING
) 
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY '\t' 
TBLPROPERTIES ("skip.header.line.count"="2");

-- Load data into the table
LOAD DATA LOCAL INPATH '/root/inputs/episodeIV_dialogues.txt' INTO TABLE episodeIV;

-- Generate output and export it
INSERT OVERWRITE LOCAL DIRECTORY '/root/HiveOutput2'
ROW FORMAT DELIMITED 
FIELDS TERMINATED BY '\t'
SELECT COUNT(*) 
FROM episodeIV 
WHERE line LIKE '%Luke%';
