services:
      #Postgres Database
      postgres:
            image: docker.io/postgres
            environment:
                  - POSTGRES_PASSWORD=postgres_password
      #redis Database
      redis:
            image: docker.io/redis
            command: ["redis-server","--protected-mode","no"]
      #Express API sercer
      api:
            build: ./server
            image: docker.io/srilpok1/complex-api
            environment:
                  - REDIS_HOST=redis
                  - REDIS_PORT=6379
                  - PGHOST=postgres
                  - PGPORT=5432 
                  - PGUSER=postgres
                  - PGPASSWORD=postgres-password 
                  - PGDATABASE=postgres
      #Worker service  
      worker:
            build: ./worker
            image: docker.io/srilpok1/complex-worker
            environment:
                  - REDIS_HOST=redis
                  - REDIS_PORT=6379
      #React client
      client:
            build: ./client
            image: docker.io/srilpok1/complex-client
      #Nginx controller
      nginx:
            depends_on:
                  - api
                  - client
            restart: always        
            build: ./nginx
            ports:
                  - "3050:80"